### ISSUE TITLE
Provide start on containerizing these scripts

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-checkmk#1]
Create a starting position with a CheckMK agent base image.

**Comment by adamhgriffith-uofu** [comment]
@gcarcassi I grabbed what I did for https://github.com/slateci/slate-server-scripts and added a CheckMK agent.

The `README.md` on the associated feature branch (see on right) describes how I was originally setting up a local development environment.

The "release" flavor of the image would be created and pushed to OSG Harbor using a command like:
```shell
$ docker build --file ./resources/docker/Dockerfile --target release-stage --tag hub.opensciencegrid.org/slate/slate-checkmk-scripts:github-26 .
...
$ docker push hub.opensciencegrid.org/slate/slate-checkmk-scripts:github-26
```

And then like you said a Kubernetes a Deployment/Job/CronJob could load the container:
```yaml
...
spec:
  containers:
    - name: worker
      image: "{{ $.Values.harbor.hostname }}/{{ $.Values.harbor.projectID }}/slate-checkmk-scripts:{{ $.Values.dockerImageTag }}"
     imagePullPolicy: IfNotPresent
     command:
       - /slate/scripts/{{ .filename }}
    env:
      - name: SLATE_API_CONF
      ...
...
```
